root_dir: /media/slsecret/E624108524105B3F/Users/simon/Downloads
datasets:
  - datasets_city
  - datasets_a
  - datasets_bb
  # - datasets_c
  # - datasets_e
  - datasets_g
  - datasets_john
  - datasets_s
  - datasets_x
  - frames0331
  - frames0331b
  - frames_sim0407
output_dir: /media/slsecret/E624108524105B3F/Users/simon/Downloads/datasets_allx3
val_split: 0.1
