path: /media/slsecret/E624108524105B3F/Users/simon/Downloads/datasets_allx3
num_epochs: 15

train: images/train
# val: images/val
val: /home/slsecret/Downloads/bfmc_data/TestSet2024/
test: /home/slsecret/Downloads/bfmc_data/TestSet2024/

# Classes
names:
  0: oneway
  1: highwayentrance
  2: stop
  3: roundabout
  4: parking
  5: crosswalk
  6: noentry
  7: highwayexit
  8: prio
  9: trafficlight
  10: block
  11: girl
  12: car
