path: /media/slsecret/E624108524105B3F/Users/simon/Downloads/datasets_combined_city

train: images/train
# val: images/val
val: images/test
test: /home/slsecret/Downloads/bfmc_data/TestSetFull/

# Classes
names:
  0: oneway
  1: highwayentrance
  2: stop
  3: roundabout
  4: parking
  5: crosswalk
  6: noentry
  7: highwayexit
  8: prio
  9: trafficlight
  10: block
  11: girl
  12: car
